services:
    setting_manager:
        class: Mpf\CrawlerBundle\Services\SettingManager
        arguments: ["@doctrine", "@form.factory"]

    task_logger:
        class: Mpf\CrawlerBundle\Services\Logger
        arguments: ["@doctrine"]
